// ./src/app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// Do not use "use client" here
const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ font: "nova square" }}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}

// Export metadata separately if needed
export { metadata };

